[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spotdl_gui"  
version = "0.1.3"
description = "A user-friendly GUI for spotdl to download Spotify music"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
  {name = "Ye8ibp0oAa", email = "Ye8ibp0oAa@proton.me"},
]
keywords = ["spotify", "downloader", "music", "audio", "gui"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Multimedia :: Sound/Audio",
]
dependencies = [
    "PyQt5>=5.15",
    "spotdl>=4.4.2",
]

[project.urls]
Homepage = "https://github.com/Ye8ibp0oAa/spotdl_gui"

[project.gui-scripts]
spotdl_gui = "spotdl_gui.main:main" 

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}

[tool.setuptools.package-data]
spotdl_gui = ["icon.ico"]