[project]
name = "flet_gnav_bar"
version = "0.0.2"
description = "A Google Navigation Bar control for Flet based on AurÃ©lien Salomon's design."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Soumalya Das", email = "geniussantu1983@gmail.com" }]
dependencies = ["flet>=0.28.3"]

[project.urls]
Homepage = "https://pro-grammer-sd.github.io/flet_gnav_bar/"
Documentation = "https://pro-grammer-sd.github.io/flet_gnav_bar/"
Repository = "https://github.com/pro-grammer-SD/flet_gnav_bar"
Issues = "https://github.com/pro-grammer-SD/flet_gnav_bar/issues"

[tool.setuptools.package-data]
"flutter.flet_gnav_bar" = ["**/*"]

[tool.uv]
dev-dependencies = [
    "flet[all]==0.28.3",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

[tool.poetry.group.dev.dependencies]
flet = { extras = ["all"], version = "0.28.3" }
mkdocs = "*"
mkdocstrings = { extras = ["python"], version = "*" }
mkdocs-material = "*"

[tool.setuptools]
license-files = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
