[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "zipfile_helper"
version = "0.1.0"
authors = [
    { name = "Nyx-0", email = "nyx.deusexmachina@proton.me" }
]
description = "Reading and extracting zip files made easier"
readme = "README.md"
requires-python = ">=3.12.3"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[tool.hatch.build.targets.wheel]
packages = ["src/zipfile_helper"]
