[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "boviz"
version = "0.2.1"
description = "An advanced and flexible scientific plotting toolkit."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "GNU General Public License v3 (GPLv3)" }
authors = [
  { name="Bo Qian", email="bqian@shu.edu.cn" }
]
dependencies = [
  "matplotlib>=3.0",
  "numpy>=1.18",
  "pandas>=1.0",
  "pytest>=6.0",
  "pathlib>=1.0",
  "argparse>=1.4.0",
  "meshio>=4.0",
  "netCDF4>=1.5"
]

[project.urls]
Homepage = "https://github.com/bo-qian/boviz"
Repository = "https://github.com/bo-qian/boviz"

[project.scripts]
boviz = "boviz.cli:main"