[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "fxp-jax"
version = "0.2.5"
description = "Simple fixed-point solver implemented in JAX"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.7.0",
    "simple-pytree>=0.2.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "pytest>=8.4.1",
    "ruff>=0.12.8",
]

[tool.pytest.ini_options]
pythonpath = "src"

[tool.pyright]
pythonPath = "src"

[tool.ruff]
src = ["src"]
