[project]
name = "cognee-community-vector-adapter-qdrant"
version = "0.0.2"
description = "Qdrant vector database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "qdrant-client>=1.14.2",
    "cognee>=0.2.1",
]
