[project]
name = "multiconn_archicad"
version = "0.3.2"
description = "MultiConn ArchiCAD is a connection object for ArchiCADâ€™s JSON API and its Python wrapper, designed to manage multiple open instances of ArchiCAD simultaneously."
readme = "README.md"
authors = [
    { name = "SzamosiMate", email = "szamimate@yahoo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.11",
    "archicad>=28.3000",
    "psutil>=6.1.1",
    "pywinauto>=0.6.9",
]

[project.optional-dependencies]
dialog-handlers = [
    "pywinauto>=0.6.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.sdist]
include = [
  "pkg/*.py",
  "/src",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.31.2",
    "hypothesis>=6.135.27",
    "hypothesis-jsonschema>=0.23.1",
    "mypy>=1.14.0",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]

[[tool.mypy.overrides]]
module = ["archicad.versioning",
          "archicad.connection",
          "archicad.releases",
          "pywinauto",
          "pywinauto.controls.uiawrapper",
          "psutil"]
follow_untyped_imports = true

[tool.ruff]
line-length = 120

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"
docstring-code-format = true
