[project]
name = "insee-mcp"
version = "0.1.12"
description = "Serveur MCP pour accéder aux données INSEE (SIRENE, BDM, Nomenclatures)"
readme = "README.md"
authors = [{ name="Kerryan", email="kerryan.mace@student-cs.fr"}]
dependencies = ["fastmcp", "pynsee", "rapidfuzz", "setuptools"]
requires-python = ">=3.10"

[project.scripts]
insee-mcp = "scripts.server:run"

[project.urls]
Homepage = "https://github.com/KerryanOPMace/mcp-insee"
Repository = "https://github.com/KerryanOPMace/mcp-insee"
Issues = "https://github.com/KerryanOPMace/mcp-insee/issues"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*"]
exclude = ["Repos*", "client*", "insee_env*", "test*"]

[tool.setuptools.package-data]
scripts = ["*.py"]

[tool.uv]
dev-dependencies = []
