[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyFRESCO"
version = "0.1.2"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.6"
authors = [{ name = "Marco Baroni", email = "mbaroni96@gmail.com"}, {name = "Beatrice Baschetti", email = "beatrice.baschetti@inaf.it"}]

dependencies = [
  "kneed>=0.8.5",
  "matplotlib>=3.7.5",
  "numpy>=1.24.4",
  "pandas>=2.0.3",
  "rasterio>=1.3.10",
  "scipy>=1.10.1",
  "spectral>=0.23.1",
  "torch>=2.4.0"
]

[project.urls]
"Source" = "https://github.com/MarcoBaroni/pyfresco"
