# file: steamgameoptions/pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "steamgameoptions"
version = "0.1.1" 
authors = [ { name="Crazy_Jarle", email="revwsbwwp@inbox.lv" } ]
description = "A simple package for interacting with Steam"
readme = "README.md" 
requires-python = ">=3.7"
license = { text = "MIT" } 
dependencies = [
  "requests",
  "python-dotenv",
]