[build-system]
requires = ["setuptools>=42.0"]
build-backend = "setuptools.build_meta"

[project]
name = "parallax-ai"
version = "0.3.5"
description = "Lightweight parallel AI API calls in Python."
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
authors = [
    {name = "Panuthep Tasawong", email = "falcon_270394@hotmail.co.th"},
]
dependencies = [
    "openai>=1.0.0",
    "jsonschema>=4.25.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
]

[project.urls]
Homepage = "https://github.com/panuthept/Parallax-AI"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["parallax_ai*"]