[project]
name = "sack-chat"
dynamic = ["version"]
description = "Lightweight chat application for terminal"
readme = "README.md"
authors = [
    { name = "mati", email = "mateusz.meksula@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "textual>=3.5.0",
]
keywords = ["chat", "socket", "tui"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]

[project.urls]
Repository = "https://github.com/mati-33/sack"

[project.scripts]
sack = "sack.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/sack"]

[tool.hatch.version]
path = "src/sack/__init__.py"

[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "F401", # unused imports
]

[tool.ruff.lint.per-file-ignores]
"src/sack/assets.py" = ["W291"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
length-sort = true
lines-after-imports = 2
lines-between-types = 1

[dependency-groups]
dev = [
    "ruff>=0.12.5",
    "textual-dev>=1.7.0",
]
