[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "svg2stl_aviinfinity"
version = "0.0.2"
authors = [
  { name="aviinfinity", email="pi@aviparshan.com" },
]
description = "A package to help you convert a SVG file to a 3D STL file"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "gmsh",
    "svg.path"
]
keywords = ["stl", "svg", "svg2stl", "3d"]

[project.scripts]
svg2stl = "svg2stl.cli:main"

[project.urls]
Homepage = "https://github.com/avipars/svg2stl"
Issues = "https://github.com/avipars/svg2stl/issues"