
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "badwulf"
version = "0.1.21"
authors = [
	{name = "Kylie A. Bemis", email = "k.bemis@northeastern.edu"}
]
description = "Minimal manager for Beowulf clusters and scientific data"
readme = "README.md"
license = {text = "Artistic License 2.0"}
requires-python = ">=3.10"
dependencies = [
	"tomli >= 1.1.0 ; python_version < '3.11'"
]
classifiers = [
	"Development Status :: 3 - Alpha",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"License :: OSI Approved :: Artistic License",
	"Intended Audience :: Science/Research",
	"Operating System :: Unix",
]

[project.urls]
Homepage = "https://github.com/kuwisdelu/badwulf"
Issues = "https://github.com/kuwisdelu/badwulf/issues"

[project.optional-dependencies]
test = ["pytest"]

[external]
dependencies = [
	"pkg:generic/zsh",
	"pkg:generic/ssh",
	"pkg:generic/rsync",
]

[tool.pytest.ini_options]
addopts = [
	"--import-mode=importlib",
]
