[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hikvision-nvr-downloader"
version = "0.1.0"
authors = [
  { name="Abhishek Chopra", email="choprabhishek630@gmail.com" },
]
description = "A robust, flexible Python library to search and download recorded clips from a Hikvision NVR."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.1"
]

[project.urls]
Homepage = "https://github.com/choprabhishek630/hikvision-nvr-downloader"
"Bug Tracker" = "https://github.com/choprabhishek630/hikvision-nvr-downloader/issues"

[tool.setuptools]
packages = ["hikvision_nvr_downloader"]