[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "service_laboratory"

# https://packaging.python.org/guides/single-sourcing-package-version/
version = "3.0.2"
description = "Service laboratory packages"
readme = "README.md"

# https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
requires-python = ">=3.12"

# https://packaging.python.org/en/latest/specifications/core-metadata/#license
license = { file = "LICENSE.txt" }
keywords = ["prototype", "setuptools", "development"]
authors = [{ name = "Alexei Rysev", email = "alexeirysev@gmail.com" }]
maintainers = [{ name = "Alexei Rysev", email = "alexeirysev@gmail.com" }]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
    "litestar>=2.15.2",
    "pydantic-settings>=2.8.1",
    "pydantic>=2.11.3",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.1",
    "advanced-alchemy==1.4.4",
    "bcrypt>=4.2.1",
    "pydantic>=2.10.6",
    "pyjwt>=2.10.1",
    "pyyaml>=6.0.2",
    "asyncpg>=0.30.0",
    "pyotp>=2.9.0",
]

[project.optional-dependencies]
dev = ["check-manifest"]
test = ["coverage"]
