[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "eks-infra-mcp"
version = "0.1.5"
description = "An MCP server exposing EKS infrastructure details"
authors = [{ name = "Harman Singh Datta"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3",
    "mcp"
]

[project.scripts]
eks-infra-mcp = "eks_infra_mcp.server:main"