[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "VNSFintech"
description = "Thư viện cung cấp các công cụ mạnh mẽ và dữ liệu chi tiết hỗ trợ phân tích tài chính, thị trường chứng khoán"
version = "0.0.17"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["requests","pandas"]