[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "reme_ai"
version = "0.1.3"
description = "Remember me"
authors = [{ name = "reme_team", email = "reme_team@alibaba-inc.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dependencies = [
    "flowllm>=0.1.3",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["reme_ai*"]
exclude = ["memoryscope*", "test*", "cookbook*", "doc*", "library*", "dist*"]

[tool.setuptools.package-data]
reme_ai = [
    "**/*.yaml",
    "**/*.py",
    "**/*.json",
]

[project.scripts]
reme = "reme_ai.app:main"
