[tool.poetry.scripts]
dhcptool = "dhcptool.main:dhcp_main"

[tool.poetry]
name = "dhcptool"
version = "2025.9.1.8"
description = "refactor(dhcptool): 支持v4(option82子选项), v6(option38)"
authors = ["mf.liang <mf.liang@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.8"
scapy = "^2.5.0"
pyyaml = "^6.0.1"


[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
