[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "goatlang"
version = "0.0.2"
description = "A language for goated people with no purpose."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name="Naren", email="narendrkumarsuresh@gmail.com" }
]

[project.scripts]
glc = "glc.main:main"

[tool.setuptools]
packages = ["glc"]
