[project]
name = "pys3fuse"
version = "0.6.1"
description = ""
authors = [
    {name = "mahdihaghverdi",email = "mahdihaghverdiliewpl@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Operating System :: POSIX :: Linux",
    "Operating System :: POSIX :: BSD :: FreeBSD",
    "Programming Language :: Python :: 3",
    "Programming Language :: C",
    "Topic :: Education",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
]

dependencies = [
    "rich (>=14.1.0,<15.0.0)",
    "structlog (>=25.4.0,<26.0.0)",
    "boto3-type-annotations-with-docs (>=0.3.1,<0.4.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "fusepy (>=3.0.1,<4.0.0)",
    "boto3 (>=1.40.1,<2.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
]

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
pytest = "^8.4.1"
coverage = "^7.10.2"


[tool.coverage.run]
branch = true
omit = [
    "pys3fuse/core/config.py",
    "pys3fuse/core/log_config.py",
    "pys3fuse/__init__.py",
    "tests/conftest.py"
]


[tool.coverage.report]
skip_covered = false
skip_empty = true
sort = '-cover'
exclude_also = [
    "def __repr__",
    "if TYPE_CHECKING",
    "raise FuseOSError",
    "except Exception",
    "except ValidationError"
]


[tool.coverage.html]
skip_covered = false
skip_empty = true


[tool.pytest.ini_options]
markers = [
    "config_parser",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
