[project]
name = "spoon-ec5fd18c"
version = "0.1.14"
requires-python = ">=3.10"
description = "An experimental package"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
]

[[project.authors]]
name = "guantao.gao"
email = "guantao.gao@clickzetta.com"

[project.urls]
Homepage = "https://github.com/czudf/spoon"
Repository = "https://github.com/czudf/spoon"
Issues = "https://github.com/czudf/spoon/issues"

[dependency-groups]
dev = ["mypy", "ruff==0.12.11", "pytest"]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
