# install pre-commit hooks
#     uv run pre-commit install
#
# run all checks
#     uv run pre-commit run --hook-stage pre-commit --all-files
#
---

default_stages:
    - pre-commit
    - pre-push
    - manual

repos:
    - repo: local
      hooks:
          - name: Check Python Type Hinting
            id: check-python-typing
            language: system
            entry: uv run mypy
            types: [python]
            exclude: ^(_UNTRACKED/|test/)

          - name: Check Python linter (ruff)
            id: check-python-linting
            stages: [manual]
            language: system
            entry: uv run ruff
            args: [check]
            types: [file, python]
            exclude: ^(_UNTRACKED/|test/)

          - name: Fix Python linter (ruff) issues
            id: fix-python-linting
            stages: [manual]
            language: system
            entry: uv run ruff
            args: [
                "check",
                "--fix",
                # "--no-cache",
                # "--select=ALL",
                # "--ignore=I001",
            ]
            types: [file, python]
            exclude: ^(_UNTRACKED/|test/)

          - name: Python Unit Tests
            id: check-python-unittest
            language: system
            entry: uv run pytest -m unit
            types: [python]
            # also runs regular tests
            exclude: ^(_UNTRACKED/)

          - name: Python Doctests
            id: check-python-doctest
            language: system
            entry: uv run pytest --doctest-modules
            types: [python]
            # also runs regular tests otherwise..
            exclude: ^(_UNTRACKED/|test/)

          - name: Check Python import order
            id: check-python-isort
            language: system
            entry: uv run ruff
            args: ["check", "--select=I001"]
            types: [file, python]
            exclude: ^(_UNTRACKED/)

          - name: Fix Python import order
            id: fix-python-isort
            stages: [manual]
            language: system
            entry: uv run ruff
            args: ["check", "--fix", "--select=I001"]
            types: [file, python]
            exclude: ^(_UNTRACKED/)

          - name: Check Python formatting (ruff)
            id: check-python-format
            language: system
            entry: uv run ruff
            args: [format, --check]
            types: [file, python]
            exclude: ^(_UNTRACKED/)

          - name: Fix Python formatting issues (ruff)
            id: fix-python-format
            stages: [manual]
            language: system
            entry: uv run ruff
            args: [format]
            types: [file, python]
            exclude: ^(_UNTRACKED/)

          # Check shell-scripts
          # uv run pre-commit run check-shellscripts --all-files
          # - id: check-shellscripts
          #   name: Check Shell Scripts
          #   entry: dev/check-shellscripts
          #   language: script
          #   types: [file, shell]

          # Check YAML files
          # uv run pre-commit run check-yaml-linting --all-files
          - name: Check YAML Linting
            id: check-yaml-linting
            # stages: [manual]
            language: system
            entry: uv run yamllint
            args: ["--strict"]
            types: [file, yaml]
            exclude: ^(_UNTRACKED/|examples/)
