[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sequins-inventory-tool"
version = "0.22.0"
description = "A tool for sequins inventory."
requires-python = ">=3.13"
dependencies = [
  "cryptography==45.0.6",
  "python-dotenv==1.1.1",
  "pydantic==2.11.7",
  "pymongo==4.14.0",
  "requests==2.32.4",
  "rich==14.1.0",
  "packaging==25.0",
  "pandas==2.3.1",
  "platformdirs==4.3.8",
  "tomlkit==0.13.3",
  "typer==0.16.0",
]
readme = "README.md"
license = "Apache-2.0"
authors = [
  {name = "The Sequins Software Team"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]

[project.scripts]
sequins-inventory-tool = "app.main:app"

[project.optional-dependencies]
test = [
  "mongomock",
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "pytest-env",
  "pytest-mock",
  "pytest-mongodb",
  "requests-mock",
  "responses",
]

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=app --cov-report=xml"
env = [
  "API_ENDPOINT=http://test",
  "API_KEY=test-key",
]
