[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pysnp"
version = "0.1.0"
description = "Stepwise Noise Peeling (SNP) for Nadarayaâ€“Watson Regression"
readme = "README.md"
authors = [{ name = "Bistoon Hosseini" }]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = ["numpy>=1.21"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["snp*"]
