[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brocode"
version = "0.1.1"
description = "brocode is a lightweight coding assistant in CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "broflow>=0.1.4",
    "brollm>=0.1.2",
    "broprompt>=0.1.5",
    "click>=8.2.1",
    "duckdb>=1.3.2",
    "pydantic>=2.11.7",
]

[project.scripts]
brocode = "brocode.cli:main"

[tool.setuptools.packages.find]
where = ["."] 
include = ["brocode*"]

[tool.setuptools.package-data]
brocode = ["prompt_hub/*.md"]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
