[project]
name = "fluent-checks"
version = "0.2.0"
description = "A library for creating fluent, readable, and composable checks for your tests or application logic."
readme = "README.md"
authors = [{ name = "vantorrewannes", email = "vantorrewannes@gmail.com" }]

requires-python = ">=3.12"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Topic :: Utilities",
]

keywords = ["fluent", "checks", "testing", "assertions", "validation"]

[project.urls]
Homepage = "https://github.com/VantorreWannes/fluent-checks"
"Bug Tracker" = "https://github.com/VantorreWannes/fluent-checks/issues"


[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=8.4.1", "ruff>=0.12.10"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

fixable = ["ALL"]
unfixable = []

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
