[project]
name = "AviTwilTools"
version = "1.0.2"
description = "Unified Python package for folder and file management"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Avi Twil", email = "avitwil@gmail.com" }
]
license = { text = "MIT" }
keywords = ["file", "txt", "json", "csv", "yaml", "xml", "dill", "binary", "database", "VarDB","filesystem", "folder", "file", "file management", "folders", "files"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
]

dependencies = [
    "dill>=0.3.6",
    "PyYAML>=6.0",
    "avi_tools>=1.0.8",
    "lxml>=4.9.3"
]

[project.urls]
"Homepage" = "https://github.com/avitwil/AT_tools"
"Source" = "https://github.com/avitwil/AT_tools"
"Bug Tracker" = "https://github.com/avitwil/AT_tools/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

