[project]
name = "xum"
version = "0.3.2"
description = "Manage Tmux session for selected folders and SSH hosts"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name="pbignardi" }
]
dependencies = []

[project.urls]
Repository="https://github.com/pbignardi/xum.git"

[dependency-groups]
dev = [
    "nuitka>=2.7.13",
    "ruff>=0.12.10",
]

[project.scripts]
xum = "xum.main:app"
