[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "youtube-transcript-extractor"
version = "0.1.2"
description = "A Python package to extract and clean YouTube video transcripts easily."
readme = "README.md"
authors = [
    { name = "54gO", email = "sagar8296d@gmail.com" }
]
license = { text = "LICENSE" }
requires-python = ">=3.9"

dependencies = [
    "youtube-transcript-api>=0.6.0",
    "urllib3>=1.26.0",
    "requests>=2.28.0",
]

[tool.setuptools.packages.find]
where = ["src"]
