[project]
name = "syncraft"
version = "0.2.3"
description = "Parser combinator library"
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
authors = [{name = "Michael Afmokt", email = "michael@esacca.com"}]
keywords = ["parser", "combinator", "sql", "sqlite", "generator", 'printer']
requires-python = ">=3.10"
dependencies = [
    "rich>=14.1.0",
    "rstr>=3.2.2",
    "sqlglot>=27.7.0",
]


[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "mkdocstrings>=0.25.0",
    "mkdocstrings-python>=1.10.0",
    "mkdocs-macros-plugin>=1.0.5",
]


