[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sllmipy"
version = "0.3.2"
description = "simple llm interface for python"

readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "pydantic",
    "google-genai",
    "google-cloud-aiplatform[tokenization]",
]
