[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "qA_Ap"
version = "0.2.2"
authors = [
  { name="Martin Ashton-Lomax", email="ashtonlomaxmartin@gmail.com" },
]
description = "query About Anything package: A Q&A application powered by LLMs and RAG on custom data."
readme = "README-PYPI.md"
requires-python = ">=3.12"
dependencies = [
  "oyaml == 1.0",
  "numpy == 2.3.2",
  "sentence-transformers == 5.0.0",
  "semantic-text-splitter == 0.27.0",
  "bottle == 0.13.4",
  "faiss-cpu == 1.12.0",
  "safer == 5.1.0",
  "ollama == 0.5.3",
  "cerebras-cloud-sdk == 1.46.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
gpu = [
  "faiss >= 1.5.3"
]

[project.urls]
Homepage = "https://github.com/Fleurman/qA_Ap"
Issues = "https://github.com/Fleurman/qA_Ap/issues"
Documentation = "https://martin.surlesinternets.ch/qA_Ap/docs"