[tool.poetry]
name = "bktree-python"
version = "0.6.1"
description = "Python implementation of Burkhard-Keller Trees (BK-Tree)"
authors = [ "Armasse <armasse35@gmail.com>" ]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "^8.3.4"
python-levenshtein = "^0.26.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.11"

[tool.pytest.ini_options]
pythonpath = [
    "src/bktree_python",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
