[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aryadocr"
version = "0.1.23"
description = "Un package Python pour l'OCR "
readme = "README.md"
authors = [
  { name = "chantry Olanda-Eyiba", email = "chantryolanda85@gmail.com" }
]
license = "MIT"
dependencies = [
"matplotlib",
"editdistance",
"tqdm",
"numpy",
"opencv-python",
"torch",
"datasets",
"huggingface-hub",
"tensorflow"
]
