[project]
name = "yta-video-ffmpeg"
version = "0.0.16"
description = "Youtube Autonomous Video Ffmpeg Module"
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    # TODO: Reduce the amount of dependencies
    # if possible, please
    "yta_constants (>=0.0.1,<1.0.0)",
    "yta_validation (>=0.0.1,<1.0.0)",
    "yta_file (>=0.0.1,<1.0.0)",
    "yta_programming (>=0.0.1,<1.0.0)",
    "yta_temp (>=0.0.1,<1.0.0)",
    "yta_date (>=0.0.1,<1.0.0)",
    "yta_video_utils (>=0.0.1,<1.0.0)",
    "yta_image_utils (>=0.0.1,<1.0.0)",
]

[tool.poetry]
packages = [{include = "yta_video_ffmpeg", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
